// app/components/sections/admin/users/usersData.js

const usersData = [
  {
    id: "u_001",
    name: "Md Billal Yasir",
    email: "billalyasir5@gmail.com",
    avatar: "https://api.dicebear.com/8.x/initials/svg?seed=Yasir",
    role: "Admin",
    status: "active",
    freeTokensGiven: 300,
    purchased: true,
    joinedAt: "2024-11-22",
  },
  {
    id: "u_002",
    name: "Ayesha Khan",
    email: "ayesha.k@example.com",
    avatar: "https://api.dicebear.com/8.x/initials/svg?seed=AK",
    role: "User",
    status: "active",
    freeTokensGiven: 150,
    purchased: false,
    joinedAt: "2025-01-10",
  },
  {
    id: "u_003",
    name: "Rahim Uddin",
    email: "rahim.u@example.com",
    avatar: "https://api.dicebear.com/8.x/initials/svg?seed=RU",
    role: "Moderator",
    status: "suspended",
    freeTokensGiven: 0,
    purchased: false,
    joinedAt: "2025-02-02",
  },
  {
    id: "u_004",
    name: "Sara Noor",
    email: "sara.noor@example.com",
    avatar: "https://api.dicebear.com/8.x/initials/svg?seed=SN",
    role: "User",
    status: "active",
    freeTokensGiven: 200,
    purchased: true,
    joinedAt: "2025-03-18",
  },
  {
    id: "u_005",
    name: "Imran Hossain",
    email: "imran.h@example.com",
    avatar: "https://api.dicebear.com/8.x/initials/svg?seed=IH",
    role: "User",
    status: "active",
    freeTokensGiven: 100,
    purchased: false,
    joinedAt: "2025-05-09",
  },
  {
    id: "u_006",
    name: "Nadia Rahman",
    email: "nadia.r@example.com",
    avatar: "https://api.dicebear.com/8.x/initials/svg?seed=NR",
    role: "User",
    status: "active",
    freeTokensGiven: 50,
    purchased: false,
    joinedAt: "2025-06-21",
  },
  {
    id: "u_007",
    name: "Zahid Hasan",
    email: "zahid.h@example.com",
    avatar: "https://api.dicebear.com/8.x/initials/svg?seed=ZH",
    role: "User",
    status: "active",
    freeTokensGiven: 250,
    purchased: true,
    joinedAt: "2025-07-30",
  },
  {
    id: "u_008",
    name: "Farhana Akter",
    email: "farhana.a@example.com",
    avatar: "https://api.dicebear.com/8.x/initials/svg?seed=FA",
    role: "User",
    status: "inactive",
    freeTokensGiven: 0,
    purchased: false,
    joinedAt: "2024-12-28",
  },
  {
    id: "u_009",
    name: "Tanvir Ahmed",
    email: "tanvir.a@example.com",
    avatar: "https://api.dicebear.com/8.x/initials/svg?seed=TA",
    role: "User",
    status: "active",
    freeTokensGiven: 75,
    purchased: false,
    joinedAt: "2025-08-03",
  },
  {
    id: "u_010",
    name: "Priya Saha",
    email: "priya.s@example.com",
    avatar: "https://api.dicebear.com/8.x/initials/svg?seed=PS",
    role: "User",
    status: "active",
    freeTokensGiven: 90,
    purchased: true,
    joinedAt: "2025-08-17",
  },
  {
    id: "u_011",
    name: "Arif Chowdhury",
    email: "arif.c@example.com",
    avatar: "https://api.dicebear.com/8.x/initials/svg?seed=AC",
    role: "User",
    status: "active",
    freeTokensGiven: 30,
    purchased: false,
    joinedAt: "2025-08-28",
  },
  {
    id: "u_012",
    name: "Meher Afroz",
    email: "meher.a@example.com",
    avatar: "https://api.dicebear.com/8.x/initials/svg?seed=MA",
    role: "User",
    status: "active",
    freeTokensGiven: 200,
    purchased: true,
    joinedAt: "2025-09-01",
  },
];
export default usersData;
